# Generated by Django 3.0.8 on 2020-09-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
